# Generated by Django 4.2.1 on 2023-06-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(blank=True, max_length=50, null=True)),
                ('cat_image', models.ImageField(upload_to='uploads/category/')),
            ],
        ),
    ]
