# Generated by Django 4.2.1 on 2023-06-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50, null=True)),
                ('last_name', models.CharField(default='', max_length=50, null=True)),
                ('email_name', models.CharField(default='', max_length=50, null=True)),
                ('password_name', models.CharField(default='', max_length=50, null=True)),
                ('mobile_name', models.BigIntegerField()),
                ('gender_name', models.CharField(default='', max_length=50, null=True)),
            ],
        ),
    ]
