# Generated by Django 4.2.1 on 2023-06-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0003_registrations_delete_registion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrations',
            name='password',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
