# Generated by Django 4.2.1 on 2023-06-27 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0004_alter_registrations_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(blank=True, max_length=150, null=True)),
                ('pro_image', models.CharField(blank=True, max_length=150, null=True)),
                ('pro_desc', models.CharField(blank=True, max_length=150, null=True)),
                ('pro_price', models.IntegerField()),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopify.category')),
            ],
        ),
    ]
